### ISSUE TITLE
What do all the rows in the event definitions mean?

### ISSUE THREAD

**Issue by domenic** [w3c/input-events#10]
As pointed out in #6, I know that default actions is not a real thing. But I don't know what "Sync / Async", "Trusted Targets", or "Context (trusted events)" mean. Are these normative? If so, I have a bunch of follow-up questions, once I get definitions for them. If not, then probably they are causing more confusion than they are helping, and should be removed.

**Comment by johanneswilm** [comment]
I think this is left-over from Benjamin. "Sync" clearly means that it's a synchronous, but I guess that's self-evident. If you don't need it on the browser side, I'll just remove it.

**Comment by johanneswilm** [comment]
@domenic 

"Trusted Targets" -- denotes the element for which this event is triggered. 

"Context" -- a list of attributes and methods on the event defined in this spec (on top of those defined in the UI events spec).

It seems to me that these are needed. What is the question related to this?

**Comment by johanneswilm** [comment]
@domenic I see now that these same terms are used in the UI events spec, also without definitions. Given that it's linked directly to that spec, it seems this is normal to have in these files. If you still feel this is an issue, maybe we should take that up with the UI events spec?

**Comment by domenic** [comment]
Yeah, I suppose we should take it up over there. Based on your descriptions, at the very least these need to be marked non-normative, since they duplicate information that should appear elsewhere. (Namely: in the spec text that fires the event for "Trusted Targets", and in the definition of the event interface itself for "Context".)
