### ISSUE TITLE
ED for Level 2 is listed incorrectly on W3C

### ISSUE THREAD

**Issue by saschanaz** [w3c/input-events#103]
https://www.w3.org/TR/?title=input+events

The Level 2 Editor's Draft URL incorrectly points [Level 1](https://cdn.staticaly.com/gh/w3c/input-events/v1/index.html) while it should point Level 2.

**Comment by marcoscaceres** [comment]
@siusin might be able to help us.

**Comment by siusin** [comment]
@deniak not sure who maintains the database of this page, could you make the editor's draft of Input Events Level 2 point to https://w3c.github.io/input-events/ please? Thanks!

**Comment by deniak** [comment]
It's now fixed!
