### ISSUE TITLE
Add Internationalization Considerations section

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/input-events#109]
There may or may not be any internationalization concerns with the spec, but we should make sure to have an "Internationalization Considerations" section stating that we've taken i18n into consideration. Of course, if there are things that should be considered, we should add them there :)

We will also ask the i18n WG to review the spec to see if they have any feedback for us.

This is part of w3c/webappswg#25

**Comment by johanneswilm** [comment]
We have discussed with the internationalization group and made the recommended modifications directly in the spec. 

Given this comment https://github.com/w3c/IntersectionObserver/issues/415#issuecomment-698363306, I am now closing this issue.

@marcoscaceres Let me know if you think we should add such a section in spite of the i18n working group not wanting us to do so.

**Comment by marcoscaceres** [comment]
Yeah, no. If they don't want it, don't do it. This is old advice and I agree inline is much better.
