### ISSUE TITLE
Add spec-prod GitHub Actions

### ISSUE THREAD

**Issue by saschanaz** [w3c/input-events#125]
Travis CI is not active here anymore.

**Comment by johanneswilm** [comment]
@saschanaz agreed. Do you happen to know whether there is a yml file for w3c repos to use github action that we can just copy, or should we translate the travis one?

**Comment by saschanaz** [comment]
This is the most general form and should just work: https://w3c.github.io/spec-prod/#deploy-to-github-pages

Per the travis config I guess we want to do something with Echidna, in that case [this one better matches]( https://w3c.github.io/spec-prod/#deploy-to-w3c-using-echidna), but someone (maybe @marcoscaceres) should configure that.

**Comment by marcoscaceres** [comment]
Sorry for the late reply. The W3C Team Contact for the group should be to set this up. I’m happy to review or help if there are issues.

**Comment by saschanaz** [comment]
It seems this is blocked on https://github.com/w3c/input-events/pull/118 ?
