### ISSUE TITLE
inputType on safari mobile is undefined

### ISSUE THREAD

**Issue by wobsoriano** [w3c/input-events#140]
I'm on iOS 16 and `event.inputType` on Safari is undefined. Safari on iOS emits a `CustomEvent` instead of an `InputEvent`. I have tried it on Chrome, Firefox, and Opera and they all emit an `InputEvent`.

```js
const input = document.querySelector('input[type="number"]');
input.addEventListener('input', logInputType);

function logInputType(event) {
  console.log(`Input type: ${event.inputType}`) // undefined
}
```

**Comment by karlcow** [comment]
@wobsoriano Not sure this is for the spec here. 
Probably https://bugs.webkit.org/show_bug.cgi?id=217693

**Comment by wobsoriano** [comment]
> @wobsoriano Not sure this is for the spec here. 
> 
> Probably https://bugs.webkit.org/show_bug.cgi?id=217693

That's definitely it! Thank you for pointing me to the right direction.
