### ISSUE TITLE
Update intention for insertReplacementText to include writing suggestions

### ISSUE THREAD

**Issue by sanketj** [w3c/input-events#150]
https://github.com/whatwg/html/issues/9065 proposes the addition of a new attribute to control UA-provided writing assistance. When suggestions provided by the UA are accepted by the user, an input event is fired and, per discussion https://github.com/whatwg/html/issues/9065#issuecomment-1719273105, insertReplacementText was determined to be the right input type.

Filing this issue to track any remaining discussions. A draft of these changes has already been written here: #149.

**Comment by johanneswilm** [comment]
@sanketj This is also what we agreed upon in an earlier meeting around TPAC, as far as I can tell. Is there something new/different about this proposal?

**Comment by sanketj** [comment]
@johanneswilm Nope, that was it. Thanks for merging the PR. Marking this issue closed.
