### ISSUE TITLE
Introduce inputType 'deleteByComposition' and fire before 'compositionstart'

### ISSUE THREAD

**Issue by chong-z** [w3c/input-events#33]
**Background**
This is about replacing text.
Usually we fire `'insertText'` and assume it will replace current selection, and canceling it will prevent the entire replacement.
However the first `'insertText'` after `'compositionstart'` is non-cancelable.

**Proposal**
We should split the replacement into _1. deletion_ and _2. insertion_ for composition, and do the deletion before `'compositionstart'`.

**Applications**
- Android - Tap a word and start composition from existing text
- All OS - Select a range and start composition through _1. typing_ or, for example, _2. Japanese "Reverse Conversion"_

**Notes**
- For start composition from existing text, the browser should pretend they are _replacing_ the text, even though what they do is just adding underlines to the text
- Canceling `'deleteByComposition'` will result in duplicated text
  - But this should be expected as you are canceling a deletion
- Canceling both `'deleteByComposition'` and the last `'beforeinput'` will keep DOM unchanged

Related discussion https://github.com/w3c/input-events/issues/17#issuecomment-247704684

**Comment by johanneswilm** [comment]
> - Canceling `'deleteByComposition'` will result in duplicated text
>   - But this should be expected as you are canceling a deletion

This confused me at first, but I think I now understand that what you mean is that:

"Canceling `'deleteByComposition'` will result in duplicated text **unless the JS code removes the text in the targetRanges from the DOM**"

I think this information should be included in an example we add to the spec, maybe a note, and not to do normative text, as it sounds slightly confusing.

**Comment by chong-z** [comment]
**RESOLUTION**: Yes we can do the issues 33/34 proposal for cancelable at each end of IME.
https://www.w3.org/2016/09/22-webapps-minutes.html#resolution02
