### ISSUE TITLE
It is unclear from the spec why inputEvent.dataTransfer is needed

### ISSUE THREAD

**Issue by smaug----** [w3c/input-events#37]
It mostly feels wrong. It should be dnd and clipboard events. No need to have it elsewhere.

**Comment by chong-z** [comment]
Yes in the table here https://w3c.github.io/input-events/#h-overview I guess we should only have `dataTransfer` for `'insertFromPaste'` and `'insertFromDrop'`.

`'insertNonText'` will be renamed to `'insertReplacementText'`, and `'insertFromYank'` will only insert plain text.

**Comment by johanneswilm** [comment]
@choniong  insertReplacementText can paste things with HTML markup. Things like `1<sup>a</sup>`. The same should be true for yank. That's why they use dataTransfer rather than data.

**Comment by johanneswilm** [comment]
I believe all questions abotu thsi were resolved at the meeting. Please reopen if incorrect.
