### ISSUE TITLE
Add `sequence<StaticRange> targetRanges` to `InputEventInit`

### ISSUE THREAD

**Issue by chong-z** [w3c/input-events#47]
Since `InputEvent` has method `getTargetRanges()`, it would be reasonable to add
```
sequence<StaticRange> targetRanges = [];
```
to `InputEventInit`.

---

Also, can we change
```
"sequence getTargetRanges();" => "sequence<StaticRange> getTargetRanges();"
```

**Comment by johanneswilm** [comment]
> Also, can we change
>```
>"sequence getTargetRanges();" => "sequence<StaticRange> getTargetRanges();"
>```
 
Do you mean to partially reverse the commit @foolip suggested in https://github.com/w3c/input-events/issues/46 ?

I read up on the webidl syntax once, wrote the  webidl code for the spec, and was told a little later that I should be basing everything off an unstable development version of webidl instead. After that I tried to forget all about it. If we are going to have serious discussions about the webidl part, I'll read up on it again. But if there is no political disagreement here, and it's just a matter of @choniong and @foolip agreeing on the best way of expressing it, I would suggest the two of you to come up with a common proposal, and we can merge that.

**Comment by chong-z** [comment]
Sorry for the trouble but I don't see any disagreements here and I'm not reversing the commit.
@foolip can you help verify if my PR meets the syntax? Thanks!

**Comment by johanneswilm** [comment]
Sorry, this was likely my mistake. I believe I partially misread @foolip's comment. The &lt; &gt; should never have been gone. As for the second part, yes, please verify.

**Comment by foolip** [comment]
Commented a bit on https://github.com/w3c/input-events/issues/48, nothing wrong with the syntax though.

> was told a little later that I should be basing everything off an unstable development version of webidl instead

This is just true for every well maintained part of the web platform. Things evolve all the time, and those things that are no longer being updated are usually a problem area, not stable foundations to build on.
