### ISSUE TITLE
Events do not have "default action"s

### ISSUE THREAD

**Issue by domenic** [w3c/input-events#6]
The concept is not defined.

Probably instead what you want to do is define an algorithm for performing certain operations. During the course of that algorithm, fire the event. Then, check if the event has been canceled. If not, perform other actions.

**Comment by johanneswilm** [comment]
@domenic The UI-Events spec defines "default action". Would you think it would be OK if I used that definition? https://w3c.github.io/uievents/#default-action

**Comment by annevk** [comment]
No, that is wrong too. 😞

**Comment by johanneswilm** [comment]
@annevk: Could you be more specific? What is wrong about the definition in UI events that is currently used?

**Comment by annevk** [comment]
It's not actually a thing that is part of the DOM event model.

**Comment by johanneswilm** [comment]
Ok, so it's also wrong the way it's used in the UI Events spec?

**Comment by annevk** [comment]
Yes.

**Comment by johanneswilm** [comment]
Given that we really just expand upon events defined in UI Events, I wonder if it could be changed in UI events, and we just reference the new definition there? @garykac What do you think?

**Comment by johanneswilm** [comment]
This issue was moved to w3c/uievents#104
