### ISSUE TITLE
Auto-publishing Level 1 Spec

### ISSUE THREAD

**Issue by chong-z** [w3c/input-events#62]
I'm not sure about the process but is it possible to get an auto-publishing link to Level 1 spec?
(e.g. github.io)

https://rawgit.com/w3c/input-events/v1/index.html might do the job but that's not the link that everyone can find via search engines. People might went into https://w3c.github.io/input-events/ and find it not working as expected.

**Comment by siusin** [comment]
No problem.

Do you want to use [https://rawgit.com/w3c/input-events/v1/index.html](https://rawgit.com/w3c/input-events/v1/index.html) as the editor's draft of the auto-published V1 working draft? (sometime editors may prefer to use Level next as the editor's draft)

**Comment by johanneswilm** [comment]
Hey,
I think priorities differ a bit between participants of the ETF. Easier access to level 1 is ok, but it shouldn't be to the detriment of level 2, which should be the main version that corresponds to the current level if discussion and which has been implemented in Webkit.
The upcoming changes to the specs that I see coming shortly are mainly of editorial nature and will affect the level 1 spec as much as level 2.

**Comment by johanneswilm** [comment]
But I guess we can have two editor's draft, one for each level? If we rename one of them to "next", we should probably also do it to the other, just to keep confusion down.

**Comment by chong-z** [comment]
@siusin Thanks for helping and sorry for the confusion. Actually what I mean is we want an auto-publishing spec other than the rawgit.com one, preferably something like https://w3c.github.io/input-events-level-1/.

The problem is Chrome team wants a spec that:
1. Describes its expected Level 1 implementation;
2. Easily accessible by developers. e.g. Via searching "InputEvent spec" in a search engine.

@johanneswilm It shouldn't conflict with Level 2. We could still have https://w3c.github.io/input-events/ or maybe https://w3c.github.io/input-events-level-2/.

**Comment by johanneswilm** [comment]
@choniong Wouldn't Google be the one to talk to if you want the Level 1 to show up higher in Google search results? Isn't there some other SEO trick for that?

What if we added a notice to the level 2 spec of the type "Are you looking for the version implemented in Chrome? Click here!"

Having the level 1 spec at https://w3c.github.io/input-events-level-1/ also seems uncontroversial to me, if that is compatible with W3C policy.

@siusin You say: "Do you want to use https://rawgit.com/w3c/input-events/v1/index.html as the editor's draft of the auto-published V1 working draft?" Do you mean that there will simply be a link to https://rawgit.com/w3c/input-events/v1/index.html as the "editor's draft" or the "next version" or do you mean that this URL is mirrored somewhere on the W3C domain?

**Comment by johanneswilm** [comment]
@choniong Here from my browser which currently is in Sweden, level 1 appears in 6th place in the search result and level 2 appears in 5th place. If I use an anonymous Chrome tab, level 2 is in 3rd place and level 1 in 5th place.

Would this be good enough? Or should it be around 1st or 2nd place? 

![w3c input events sok pa google](https://cloud.githubusercontent.com/assets/595512/25447886/1f269c08-2ab7-11e7-95d1-e1082bd396bd.png)

**Comment by chong-z** [comment]
@johanneswilm Does https://www.w3.org/TR/input-events-1/ reflect latest change to https://github.com/w3c/input-events/tree/v1? I'm concerned that not everyone knows they should click 'Latest editor's draft' and find the latest spec.

BTW Here is a related issue https://github.com/w3c/webrtc-pc/issues/942.

**Comment by johanneswilm** [comment]
@choniong I believe it currently does (both have March 21st as their publishing date), and my understanding was that @siusin either has turned auto publishing to this address on, or if she hasn't, then that this is an option.

But at any rate, it seems to me that web developers looking for level 1 should look at https://www.w3.org/TR/input-events-1/ rather than a github address. If there is no auto-update to the w3c address, at the least we could always manually initiate an update when a new version of Chrome with a changed implementation is released. Or do you think this will be a major problem?

**Comment by siusin** [comment]
@choniong @johanneswilm 

Sorry about the confusion... I don't mean to rename any of the spec. Make both versions auto-publishing is possible, but each version needs to have an editor's draft as the input of the auto-pub system.

If I understand correctly, we are going to let:
1) Level 1 auto-published under /TR/input-events-1, using [https://rawgit.com/w3c/input-events/v1/index.html](https://rawgit.com/w3c/input-events/v1/index.html) as the input.
2) Level 2 auto-published under /TR/input-event-2, using [https://w3c.github.io/input-events/](https://w3c.github.io/input-events/) as the input. Also /TR/input-event points to  /TR/input-event-2.

Does it make sense to you?

**Comment by chong-z** [comment]
@siusin That's exactly what we want, thanks!

**Comment by johanneswilm** [comment]
Yes, @siusin has this been set up?

**Comment by chaals** [comment]
The problem with auto-update is that it makes it hard to explain what changes were made, since you no longer have an obvious difference between editors'drafts and the "formal publications", unless you keep the editor's draft in some side-branch.

Pointing to the rawgit version is a useful thing to do in the README for the repo...

**Comment by johanneswilm** [comment]
@chaals: Wait -- so you are saying that the W3C has this mechanism of auto-updating, and presumably it's being used with some speccs, but it is controversial?

For me really either solution is fine - manual or auto-publication. 

Are you suggesting that we add an explanation of the two levels into the readme (in the v2 branch) and then link to both of them in there?

**Comment by johanneswilm** [comment]
I have now added links both in the readme and both specs. Hopefully this helps.

**Comment by siusin** [comment]
It should be all set now.

Apologise for the delay, I thought I have got it done long ago, but I didn't...
