### ISSUE TITLE
formatFontColor values of rtl etc

### ISSUE THREAD

**Issue by r12a** [w3c/input-events#69]
dfn-data
https://w3c.github.io/input-events/#dfn-data

bullet 4

> If the inputType is "formatSetInlineTextDirection" or "formatFontColor" the value of data is to be one of "ltr", "rtl", "auto" or "null".

I suspect that  

> or "formatFontColor"

shouldn't be there.

**Comment by johanneswilm** [comment]
This issue seems to have been fixed earlier.
