### ISSUE TITLE
'deleteWordForwards' and 'deleteWordBackwards' not well defined

### ISSUE THREAD

**Issue by r12a** [w3c/input-events#72]
[from Addison Phillips]

https://w3c.github.io/input-events/#interface-InputEvent-Attributes

Word deletion in some languages non-space-delimited languages requires a dictionary or other intervention to get right. This should be carefully defined.

Also it may be worth clarifying that logical order should be used when talking about forwards and backwards (because of the different visual orders when bidi text is displayed).

**Comment by johanneswilm** [comment]
@aphillips @r12a Right, but this is about the **intention** to delete a word backward or forward (by clicking certain keys or choosing something in a menu). It does not say anything about the UA's or JavaScript apps ability to actually correctly guess what constitutes a word. As has been discussed previously in the editing taskforce, we are currently not in a position where we can standardize and/or agree on what constitutes a word or make any rules concerning that.

**Comment by johanneswilm** [comment]
@r12a @aphillips To me, `backward` and `forward` are -- differently than `right` or `left` -- logical directions already. Could you clarify how these directions could be misunderstood in bidi or rtl text?

**Comment by johanneswilm** [comment]
Based on the meeting at TPAC, we are waiting for a a suggestion on how to adjust the explanatory note text from @r12a .

**Comment by aphillips** [comment]
I carefully read the section again this morning (btw, my other action today is to get respec to fix the warning about I18N glossary terms). I think the text present is sufficient and suggest that you close this issue.

**Comment by johanneswilm** [comment]
@aphillips Thanks!

**Comment by r12a** [comment]
[For clarity:  i asked @aphillips to look at this, since it was originally his comment, rather than mine. So i don't think there's a need to await further response from myself.]
