### ISSUE TITLE
Deleting by Paste

### ISSUE THREAD

**Issue by sebilasse** [w3c/input-events#81]
This is a question about level 2 `.inputType` and ClipboardEvents (writing a polyfill for FF) :

There is `insertFromPaste` and `deleteByCut` –
but which would be the correct `.inputType` if text is selected and the user pastes other text which is a "replace operation" ?

Shouldn't there be `deleteByPaste` as well ?

**Comment by johanneswilm** [comment]
This is `insertFromPaste` The targetrange/selection will point to the content that will be overwritten.
