### ISSUE TITLE
Move interface definition of inputType into ui-events

### ISSUE THREAD

**Issue by johanneswilm** [w3c/input-events#84]
As there will be more specs using beforeinput/input events, the part of the interface that defines the `inputType` will have to be moved to the ui-events spec.

I assume this simply means deleting 2 lines [1]. @garykac @travisleithead Has everything that needs to be done on the ui-events side been done and can I go ahead deleting those two lines? 

[1] https://github.com/w3c/input-events/blob/fe6e148fa4e7c9925f14c12b9e2e04c7d8ff5094/index.html#L214 and https://github.com/w3c/input-events/blob/fe6e148fa4e7c9925f14c12b9e2e04c7d8ff5094/index.html#L220

**Comment by johanneswilm** [comment]
@garykac @travisleithead ping!

**Comment by garykac** [comment]
UIEvents spec updated in https://github.com/w3c/uievents/commit/faf20a23cd895480db0b105530a081be426333f1

**Comment by johanneswilm** [comment]
fixed in https://github.com/w3c/input-events/commit/2da2d3fd5cca5f5b876140de5d5153afacde32ab
