### ISSUE TITLE
Documentation says beforeinput event is cancelable, browser says it's not

### ISSUE THREAD

**Issue by lotomb** [w3c/input-events#92]
I read that `beforeinput` is intended to be cancelable: [Editor's draft / 14 October 2018](https://w3c.github.io/uievents/#beforeinput).

On Google Chrome at least, this doesn't seem to be the case. I found that a beforeinput event _is_ cancelable when it is triggered by paste (Ctrl+V / drag / context menu) but when triggered by inserting a character or deleting text, it is not.

Is this by design?

MWE:
```
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>
    $(document).ready(function() {
        document.getElementById("i").addEventListener("beforeinput", function(e) {
            alert(e.cancelable);
        });
    });
  </script>
</head>
<body>
  <input id="i">
</body>
</html>
```

Related SO post: https://stackoverflow.com/questions/53140803

**Comment by johanneswilm** [comment]
Hey @nbarto ,
sorry for late response. Chrome follows version 1 of the spec, which does not promise as much cancelability as version 2.
